### ISSUE TITLE
Element alignment problem in firefox 59

### ISSUE THREAD

**Issue by LarkinZero** [mayswind/AriaNg#206] opened 2018-03-14 09:07 UTC
![qq20180314-170322](https://user-images.githubusercontent.com/6387162/37392747-011b7058-27aa-11e8-99b1-1cb2131db2f4.png)

System:MacOS 10.13.3
Browser:Firefox 59

**Comment by mayswind** [comment] 2018-03-14 09:41
I can't reproduce. Please provide your browser and screen resolution data.

**Comment by LarkinZero** [comment] 2018-03-14 10:42
Display:2880 x 1800
Scale to 1680 x1050

**Comment by mayswind** [comment] 2018-04-05 13:56
fixed in the latest daily build

**Closed by mayswind** 2018-04-05 13:56 UTC
Labels: bug
